import type { Metadata } from "next";
import Link from "next/link";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "SSR Error Boundaries Demo Next 14",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900 min-h-screen`}
      >
        <nav className="shadow mb-8">
          <div className="mx-auto p-4 flex flex-col sm:flex-row items-center justify-between">
            <div className="flex gap-4 items-center">
              <h1 className="text-2xl font-bold flex">
                <Link href="/" className="hover:text-neutral-400 transition-colors">Server Side Rendering Error Boundary Demo</Link>
              </h1>
              <span className="bg-neutral-800 text-neutral-100 px-2 py-1 rounded text-sm font-semibold">
                Next 15.5.0
              </span>
            </div>
            <ul className="text-sm flex gap-8 text-base font-semibold">
              <li>
                <Link href="/no-error-boundary" className="hover:text-yellow-600 transition-colors">No Error Boundary</Link>
              </li>
              <li>
                <Link href="/error-boundary-only" className="hover:text-yellow-600 transition-colors">Error Boundary Only</Link>
              </li>
              <li>
                <Link href="/error-boundary-plus-div" className="hover:text-yellow-600 transition-colors">Error Boundary Plus Div</Link>
              </li>
              <li>
                <Link href="/error-boundary-plus-provider" className="hover:text-yellow-600 transition-colors">Error Boundary Plus Provider</Link>
              </li>
            </ul>
          </div>
        </nav>
        <main className="mx-auto px-4 flex flex-col gap-4">
          {children}
        </main>
      </body>
    </html>
  );
}
